name: Check Markdown Links

on:
  push:
  schedule:
    - cron: '0 0 * * *'

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        width:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version-file: .node-version
      - run: npm ci
      - uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          config-file: .markdown-link-check/config.json
